# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Required or else mkdocs and readthedocs will not be compatible and the build
# will break.
# https://github.com/readthedocs/readthedocs.org/issues/5474
python:
  version: 3.6

# Optionally build your docs in additional formats such as PDF and ePub
formats: []
