coverage:
  precision: 2
  round: down
  range: "30...100"

  status:
    project:
      target: "15%"
      if_no_uploads: error

    patch:
      target: "15%"
      if_no_uploads: error

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default
