FROM mysql:5.7

ARG BASE_DIR

COPY SQL/0000-00-00-schema.sql /0000-00-00-schema.sql
COPY SQL/0000-00-01-Permission.sql /0000-00-01-Permission.sql
COPY SQL/0000-00-02-Menus.sql /0000-00-02-Menus.sql
COPY SQL/0000-00-03-ConfigTables.sql /0000-00-03-ConfigTables.sql
COPY SQL/0000-00-04-Help.sql /0000-00-04-Help.sql

COPY test/sql/CreateTestUser.sql /0000-01-00-TestUser.sql
COPY docs/instruments/radiology_review.sql /radiology_review.sql

RUN echo "Use LorisTest;" | cat - \
    0000-00-00-schema.sql \
    0000-00-01-Permission.sql \
    0000-00-02-Menus.sql \
    0000-00-03-ConfigTables.sql \
    0000-00-04-Help.sql \
    0000-01-00-TestUser.sql \
    radiology_review.sql > /docker-entrypoint-initdb.d/0000-compiled.sql

RUN echo "Use LorisTest;" >> /docker-entrypoint-initdb.d/0001-paths.sql
RUN echo "UPDATE Config SET Value='${BASE_DIR}/' WHERE ConfigID=(SELECT ID FROM ConfigSettings WHERE Name='base');" >> /docker-entrypoint-initdb.d/0001-paths.sql
RUN echo "UPDATE Config SET Value='http://web:8000' WHERE ConfigID=(SELECT ID FROM ConfigSettings WHERE Name='url');" >> /docker-entrypoint-initdb.d/0001-paths.sql
