FROM php:7.2

RUN docker-php-ext-install mysql mysqli
RUN apt-get update && \
    apt-get install -y zlib1g-dev

# Install extensions through the scripts the container provides
RUN docker-php-ext-install pdo_mysql
