FROM php:7.3

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev zip

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install libzip-dev && \
    docker-php-ext-install zip
