# Build a container with the raisinbread data pre-loaded.
# Based on https://serverfault.com/questions/796762/creating-a-docker-mysql-container-with-a-prepared-database-scheme
FROM mysql:5.7 as builder

# That file does the DB initialization but also runs mysql daemon, by removing the last line it will only init
RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]

# needed for intialization
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=LorisTest

COPY SQL/0000-00-00-schema.sql /0000-00-00-schema.sql
COPY SQL/0000-00-01-Modules.sql /0000-00-01-Modules.sql
COPY SQL/0000-00-02-Permission.sql /0000-00-02-Permission.sql
COPY SQL/0000-00-03-ConfigTables.sql /0000-00-03-ConfigTables.sql
COPY SQL/0000-00-04-Help.sql /0000-00-04-Help.sql
COPY SQL/0000-00-05-ElectrophysiologyTables.sql /0000-00-05-ElectrophysiologyTables.sql
COPY raisinbread/instruments/instrument_sql/aosi.sql  /aosi.sql
COPY raisinbread/instruments/instrument_sql/bmi.sql  /bmi.sql
COPY raisinbread/instruments/instrument_sql/medical_history.sql  /medical_history.sql
COPY raisinbread/instruments/instrument_sql/mri_parameter_form.sql  /mri_parameter_form.sql
COPY raisinbread/instruments/instrument_sql/radiology_review.sql  /radiology_review.sql
COPY test/test_instrument/testtest.sql /test_instrument.sql
COPY raisinbread/RB_files/*.sql /RB_files/

RUN echo "Use LorisTest;" | cat - \
    0000-00-00-schema.sql \
    0000-00-01-Modules.sql \
    0000-00-02-Permission.sql \
    0000-00-03-ConfigTables.sql \
    0000-00-04-Help.sql \
    0000-00-05-ElectrophysiologyTables.sql \
    aosi.sql \
    bmi.sql \
    medical_history.sql \
    mri_parameter_form.sql \
    radiology_review.sql \
    test_instrument.sql \
    RB_files/*.sql > /docker-entrypoint-initdb.d/0000-compiled.sql

RUN echo "Use LorisTest;" >> /docker-entrypoint-initdb.d/0001-paths.sql
RUN echo "UPDATE Config SET Value='${BASE_DIR}/' WHERE ConfigID=(SELECT ID FROM ConfigSettings WHERE Name='base');" >> /docker-entrypoint-initdb.d/0001-paths.sql
RUN echo "GRANT UPDATE,INSERT,SELECT,DELETE,DROP,CREATE TEMPORARY TABLES ON LorisTest.* TO 'SQLTestUser'@'%' IDENTIFIED BY 'TestPassword' WITH GRANT OPTION;" >> /docker-entrypoint-initdb.d/0004-sql-user.sql

# Need to change the datadir to something else that /var/lib/mysql because the parent docker file defines it as a volume.
# https://docs.docker.com/engine/reference/builder/#volume :
#       Changing the volume from within the Dockerfile: If any build steps change the data within the volume after
#       it has been declared, those changes will be discarded.
RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]




FROM mysql:5.7

COPY --from=builder /initialized-db /var/lib/mysql
