FROM php:8.3

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN yes | pecl install xdebug-3.1.0
RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini
RUN echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini

# Install extensions through the scripts the container provides
RUN apt-get install -y libzip-dev zip && \
    docker-php-ext-install pdo_mysql zip
