FROM php:8.1

RUN mkdir -p  /var/www/html/project/instruments
COPY raisinbread/instruments/* /var/www/html/project/instruments

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip
