FROM php:8.0

RUN apt-get update && \
    apt-get install -y mariadb-client libzip-dev

RUN apt-get install -y libzip-dev zip && \
    docker-php-ext-install pdo_mysql && \
    docker-php-ext-install zip
