<?php declare(strict_types=1);

/**
 * Defines the Analysis class for specimen analyses in the Biobank module.
 *
 * This class represents a specimen analysis process and extends the `Process` class.
 *
 * @package    LORIS
 * @subpackage Biobank
 * @author     Henri Rabalais <henri.j.rabalais@gmail.com>
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link       https://www.github.com/aces/Loris/
 */

namespace LORIS\biobank;

/**
 * Analysis class for specimen processing in the Biobank module.
 *
 * @category   Entity
 * @package    LORIS
 * @subpackage Biobank
 * @author     Henri Rabalais <henri.j.rabalais@gmail.com>
 * @license    http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link       https://www.github.com/aces/Loris/
 */
class Analysis extends Process
{
    // No additional properties or methods are needed at this time.
}
