<?php
/**
 * Script changing all table engines in the database to InnoDB
 *
 * PHP Version 7
 *
 * @category Main
 * @package  Loris
 * @author   Various <example@example.com>
 * @license  Loris license
 * @link     https://www.github.com/aces/Loris-Trunk/
 */
require_once __DIR__ . "/../generic_includes.php";

$dbConfig = $config->getSetting('database');
$adminDB  = Database::singleton(
    $dbConfig['database'],
    $dbConfig['quatUser'],
    $dbConfig['quatPassword'],
    $dbConfig['host'],
    true
);

// SETUP OUTPUT to file in project/tables_sql/change_MyISAM_to_INNODB_allTables.sql
$filePath = __DIR__ . "/../../SQL/Archive/autogenerated/single_use/change_MyISAM_to_INNODB_allTables.sql";

echo "
#####################################################################################
This script will create ALTER TABLE statements to change all tables in the database 
  with a MyISAM engine to use INNODB. 
This script includes foreign keycheck disabling and re-enabling.
#####################################################################################
\n\n";

//define the command line parameters
if (count($argv) < 2 || $argv[1] == 'help') {
    showHelp();
}

// set default arguments
$confirm    = false;
$printToSQL = false;
$output     = "";

// get the rest of the arguments
if (!is_null($argv[1]) && $argv[1] === 'confirm') {
    $confirm = true;
} elseif (!is_null($argv[1]) && $argv[1] === 'tosql') {
    $printToSQL = true;
} else {
    showHelp();
}

// SETUP INPUT from Database table schema
$table_names = $DB->pselectCol(
    "SELECT TABLE_NAME 
     FROM INFORMATION_SCHEMA.TABLES
     WHERE TABLE_SCHEMA =:dbn 
       AND ENGINE = 'MyISAM'",
    array("dbn" => $dbConfig['database'])
);
// END INPUT

// SETUP OUTPUT
$output .="SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS; \n";
$output .="SET FOREIGN_KEY_CHECKS=0; \n";
if (empty($table_names)) {
    echo "No MyISAM tables detected. Terminating the script.\n";
    die();
}
foreach ($table_names as $key=>$table)
{
    $output .= "ALTER TABLE `".$table."` ENGINE=INNODB;\n";
}
$output .="SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; \n";
// END OUTPUT

// Take action, run on DB or generate file
if ($printToSQL) {
    // Generate the file
    writeToFile($filePath, $output);
} elseif ($confirm) {
    // Run on database
    // Get data from all tables to be modified
    $dataPre = array();
    foreach ($table_names as $key=>$table)
    {
        $dataPre[$table] = $DB->pselect("SELECT * FROM ". $table, array());
    }
    echo "Running database calls.\n";
    // Admin necessary, ALTER TABLE calls
    $adminDB->run($output);
    $dataPost = array();
    foreach ($table_names as $key=>$table)
    {
        $dataPost[$table] = $DB->pselect("SELECT * FROM ". $table, array());
    }
    compareArrays($dataPre, $dataPost);
}

function compareArrays($array1, $array2)
{
    echo "Comparing data before and after engine conversion.\n";
    foreach ($array1 as $table=>$rows) {
        foreach ($rows as $rowid=>$row) {
            foreach ($row as $key=>$val) {
                if ($array2[$table][$rowid][$key] !== $val) {
                    echo "The data has been corrupted for Table $table, at field $key\n";
                }
            }
        }
    }
}

function showHelp()
{
    echo "*** CHANGE MyISAM TO INNODB - all tables ***\n\n";

    echo "Example: php Engine_Change_MyISAM_to_INNODB_allTables.php confirm\n";
    echo "Example: php Engine_Change_MyISAM_to_INNODB_allTables.php tosql\n\n";

    echo "When the 'tosql' option is used, the SQL file exported will be located \n".
        "under the following path: \n".
        "%loris_root%/SQL/Archive/autogenerated/single_use/change_MyISAM_to_INNODB_allTables.sql\n\n";

    echo "When the 'confirm' option is used, the generated SQL is run directly on the database.\n\n";

    die();
}