<?php declare(strict_types=1);
/**
 * Reads and ouputs the latest file generated by the MRI upload process.
 *
 * PHP version 7
 *
 * @category Script
 * @package  Main
 * @author   Olga Tsibulevskaya  <olgatsib@gmail.com>
 * @license  Loris License
 * @link     https://github.com/aces/Loris-Trunk
*/

if (!\User::singleton()->hasPermission('imaging_uploader')) {
    http_response_code(403);
    return;
}

header("Cache-Control: no-store, no-cache, must-revalidate");
require_once "../tools/generic_includes.php";


$log_file = getLatestLogFile();
$contents = file_get_contents($log_file);
if (!$contents) {
    throw new \LorisException(
        "Could not read file contents from " .
        htmlspecialchars($log_file, ENT_QUOTES)
    );
}
echo $contents;

/**
 * Get the last changed log file using in the
 * $paths['base'] . "/" . $paths['log'] . "/MRI_upload" directory

 * @return string The name of the last log file modified in the log directory.
 */
function getLatestLogFile(): string
{
    $paths = NDB_Config::singleton()->getSetting('paths');
    // Get the path from the config file.
    if (empty($paths)) {
        throw new ConfigurationException(
            "Paths could not be loaded from Config file!"
        );
    }

    // Get the directory name.
    $log_directory = $paths['base'] . "/" . $paths['log'] . "/MRI_upload";
    if (!file_exists($log_directory)) {
        throw new ConfigurationException(
            "Could not find a valid directory at " .
            htmlspecialchars($log_directory, ENT_QUOTES)
        );
    }

    // Get the last file modified.
    $files = glob($log_directory . "/*MRI_upload*");
    $files = array_combine($files, array_map("filemtime", $files));
    arsort($files);
    return key($files);
}