const test = {
  'recruitment': {
    'progress': {
      '1': {
        'id': '1',
        'total_recruitment': 1588,
        'title': 'COMPASS-ND',
        'recruitment_target': 1600,
        'female_total': 777,
        'female_percent': 49,
        'male_total': 811,
        'male_percent': 51,
      },
      '2': {
        'id': '2',
        'total_recruitment': 390,
        'title': 'CAN-THUMBS-UP',
        'recruitment_target': 20,
        'female_total': 268,
        'female_percent': 1340,
        'male_total': 122,
        'male_percent': 610,
        'surpassed_recruitment': 'true',
        'female_full_percent': 69,
        'male_full_percent': 31,
      },
      'overall': {
        'id': 'overall',
        'total_recruitment': 1978,
        'title': 'Overall Recruitment',
        'recruitment_target': 1000,
        'female_total': 1045,
        'female_percent': 105,
        'male_total': 933,
        'male_percent': 93,
        'surpassed_recruitment': 'true',
        'female_full_percent': 53,
        'male_full_percent': 47,
      },
    },
    'total_scans': 12640,
  },
  'studyProgression': {
    'id': 'overall',
    'total_recruitment': 1978,
    'title': 'Overall Recruitment',
    'recruitment_target': 1000,
    'female_total': 1045,
    'female_percent': 105,
    'male_total': 933,
    'male_percent': 93,
    'surpassed_recruitment': 'true',
    'female_full_percent': 53,
    'male_full_percent': 47,
    'total_scans': 12640,
  },
};
