<?php
/**
 * LorisApp class file
 *
 * PHP version 7
 *
 * @category Main
 * @package  Main
 * @author   Jacob Penny <jpenny.mcin@gmail.com>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://www.github.com/aces/Loris/
 */

/**
 * LorisApp Class
 *
 * Wrapper around \Slim\App in order to decrease coupling
 *
 * @category Main
 * @package  Main
 * @author   Jacob Penny <jpenny.mcin@gmail.com>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://www.github.com/aces/Loris/
 */
class LorisApp extends \Slim\App
{

}
