<?php
/**
 * This file contains the BadRequest exception type.
 *
 * PHP Version 7
 *
 * @category Errors
 * @package  Loris
 * @author   Loris Team <loris-dev@bic.mni.mcgill.ca>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

/**
 * The BadRequest exception is thrown when the user's input is invalid or insufficient.
 * be found. It maps to a 400 error.
 *
 * @category Errors
 * @package  Loris
 * @author   Loris Team <loris-dev@bic.mni.mcgill.ca>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

class BadRequest extends LorisException
{
}

