<?php
/**
 * This class is a wrapper around any Invalid exceptions thrown in Loris
 *
 * PHP Version 5
 *
 * @category Errors
 * @package  Loris
 * @author   Henri Rabalais <hrabalais.mcin@gmail.com>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

/**
 * The Invalid class.
 *
 * @category Errors
 * @package  Loris
 * @author   Henri Rabalais <hrabalais.mcin@gmail.com>
 * @license  http://www.gnu.org/licenses/gpl-3.0.txt GPLv3
 * @link     https://github.com/aces/Loris
 */

class Invalid extends \LorisException
{
}
?>
