#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 * Script that generates a LINST instrument's pot (PO template) file for
 * translation. This should make it easier to send translations to translators
 */

// require_once __DIR__ . "/generic_includes.php";

$stdin = fopen("php://stdin", "r");
$seenStrings = [];
$createdAt = new \DateTimeImmutable()->format("Y-m-d H:iO");
print <<<EOH
# Autogenerated default strings to be translated for LORIS instrument

msgid ""
msgstr ""
"Project-Id-Version: LORIS 27\\n"
"Report-Msgid-Bugs-to: https://github.com/aces/Loris/issues\\n"
"POT-Creation-Date: $createdAt\\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"
"Language-Team: LANGUAGE <LI@li.org\\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"


EOH;

function addMsg(string $label) {
    global $seenStrings;
    if(!empty($label) && !isset($seenStrings[$label])) {
        print "msgid \"$label\"\n";
        print "msgstr \"\"\n\n";
        $seenStrings[$label] = true;
    }
}

while (($line = fgets($stdin)) !== false)
{
    $pieces = explode('{@}', $line);
    $label = trim($pieces[2] ?? '');
    if ($label !== null && $label !== '') {
	    addMsg($label);
    }
    if(!empty(trim($pieces[3] ?? ''))) {
	    $options = explode('{-}', $pieces[3]);
	    foreach($options as $option) {
		    $values = [];
		    if(preg_match("/'(.+)'=>'(.+)'/", $option, $values) === 1) {
			    addMsg($values[2]);
		    }
	    }
    }
}
fclose($stdin);
