CREATE TABLE `enumeration` (
    `EnumerationID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(25) NOT NULL,
    PRIMARY KEY (`enumerationID`),
    UNIQUE KEY (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `enumeration_label` (
    `enumerationID` INT(11) UNSIGNED NOT NULL,
    `LanguageID` INT(10) UNSIGNED NOT NULL,
    `Label` varchar(45) NOT NULL,
    PRIMARY KEY (`EnumerationID`, `LanguageID`),
    CONSTRAINT `FK_enum_label_LanguageID` FOREIGN KEY (`LanguageID`) REFERENCES `language` (`language_id`),
    CONSTRAINT `FK_enum_label_enumerationID` FOREIGN KEY (`enumerationID`) REFERENCES `enumeration` (`enumerationID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

 
-- fill option with existing ENUM values
INSERT INTO `enumeration` VALUES (null, 'yes');
INSERT INTO `enumeration` VALUES (null, 'no');
INSERT INTO `enumeration` VALUES (null, 'true');
INSERT INTO `enumeration` VALUES (null, 'false');
INSERT INTO `enumeration` VALUES (null, 'pass');
INSERT INTO `enumeration` VALUES (null, 'fail');
INSERT INTO `enumeration` VALUES (null, 'A');
INSERT INTO `enumeration` VALUES (null, 'C');
INSERT INTO `enumeration` VALUES (null, 'G');
INSERT INTO `enumeration` VALUES (null, 'T');
INSERT INTO `enumeration` VALUES (null, 'female');
INSERT INTO `enumeration` VALUES (null, 'male');
INSERT INTO `enumeration` VALUES (null, '1st_cousin');
INSERT INTO `enumeration` VALUES (null, 'abnormal');
INSERT INTO `enumeration` VALUES (null, 'acknowledged');
INSERT INTO `enumeration` VALUES (null, 'all');
INSERT INTO `enumeration` VALUES (null, 'answered');
INSERT INTO `enumeration` VALUES (null, 'approval');
INSERT INTO `enumeration` VALUES (null, 'assigned');
INSERT INTO `enumeration` VALUES (null, 'assignee');
INSERT INTO `enumeration` VALUES (null, 'battery');
INSERT INTO `enumeration` VALUES (null, 'benign');
INSERT INTO `enumeration` VALUES (null, 'candid');
INSERT INTO `enumeration` VALUES (null, 'category');
INSERT INTO `enumeration` VALUES (null, 'CDMR');
INSERT INTO `enumeration` VALUES (null, 'centerid');
INSERT INTO `enumeration` VALUES (null, 'certified');
INSERT INTO `enumeration` VALUES (null, 'cleaned');
INSERT INTO `enumeration` VALUES (null, 'closed');
INSERT INTO `enumeration` VALUES (null, 'comment');
INSERT INTO `enumeration` VALUES (null, 'complete');
INSERT INTO `enumeration` VALUES (null, 'created');
INSERT INTO `enumeration` VALUES (null, 'D');
INSERT INTO `enumeration` VALUES (null, 'de_novo');
INSERT INTO `enumeration` VALUES (null, 'DMR');
INSERT INTO `enumeration` VALUES (null, 'do_not_know');
INSERT INTO `enumeration` VALUES (null, 'emailed');
INSERT INTO `enumeration` VALUES (null, 'exclude');
INSERT INTO `enumeration` VALUES (null, 'excluded');
INSERT INTO `enumeration` VALUES (null, 'exonic');
INSERT INTO `enumeration` VALUES (null, 'failure');
INSERT INTO `enumeration` VALUES (null, 'feedback');
INSERT INTO `enumeration` VALUES (null, 'full_sibling');
INSERT INTO `enumeration` VALUES (null, 'gain');
INSERT INTO `enumeration` VALUES (null, 'green');
INSERT INTO `enumeration` VALUES (null, 'half_sibling');
INSERT INTO `enumeration` VALUES (null, 'hardcopy');
INSERT INTO `enumeration` VALUES (null, 'high');
INSERT INTO `enumeration` VALUES (null, 'human');
INSERT INTO `enumeration` VALUES (null, 'I');
INSERT INTO `enumeration` VALUES (null, 'immediate');
INSERT INTO `enumeration` VALUES (null, 'in_progress');
INSERT INTO `enumeration` VALUES (null, 'inserted');
INSERT INTO `enumeration` VALUES (null, 'inserted_flag');
INSERT INTO `enumeration` VALUES (null, 'instrument');
INSERT INTO `enumeration` VALUES (null, 'in_training');
INSERT INTO `enumeration` VALUES (null, 'invalid');
INSERT INTO `enumeration` VALUES (null, 'island');
INSERT INTO `enumeration` VALUES (null, 'lastupdatedby');
INSERT INTO `enumeration` VALUES (null, 'loss');
INSERT INTO `enumeration` VALUES (null, 'low');
INSERT INTO `enumeration` VALUES (null, 'maternal');
INSERT INTO `enumeration` VALUES (null, 'metavars');
INSERT INTO `enumeration` VALUES (null, 'module');
INSERT INTO `enumeration` VALUES (null, 'mri_upload');
INSERT INTO `enumeration` VALUES (null, 'na');
INSERT INTO `enumeration` VALUES (null, 'ncrnaexonic');
INSERT INTO `enumeration` VALUES (null, 'new');
INSERT INTO `enumeration` VALUES (null, 'none');
INSERT INTO `enumeration` VALUES (null, 'nonsynonymous');
INSERT INTO `enumeration` VALUES (null, 'normal');
INSERT INTO `enumeration` VALUES (null, 'not_answered');
INSERT INTO `enumeration` VALUES (null, 'not_applicable');
INSERT INTO `enumeration` VALUES (null, 'not_certified');
INSERT INTO `enumeration` VALUES (null, 'not excluded');
INSERT INTO `enumeration` VALUES (null, 'not started');
INSERT INTO `enumeration` VALUES (null, 'n_shelf');
INSERT INTO `enumeration` VALUES (null, 'n_shore');
INSERT INTO `enumeration` VALUES (null, 'opened');
INSERT INTO `enumeration` VALUES (null, 'optimal');
INSERT INTO `enumeration` VALUES (null, 'other');
INSERT INTO `enumeration` VALUES (null, 'partial');
INSERT INTO `enumeration` VALUES (null, 'paternal');
INSERT INTO `enumeration` VALUES (null, 'pathogenic');
INSERT INTO `enumeration` VALUES (null, 'pdf');
INSERT INTO `enumeration` VALUES (null, 'pending');
INSERT INTO `enumeration` VALUES (null, 'priority');
INSERT INTO `enumeration` VALUES (null, 'profile');
INSERT INTO `enumeration` VALUES (null, 'questionable');
INSERT INTO `enumeration` VALUES (null, 'quiz');
INSERT INTO `enumeration` VALUES (null, 'raw');
INSERT INTO `enumeration` VALUES (null, 'RDMR');
INSERT INTO `enumeration` VALUES (null, 'recycling bin');
INSERT INTO `enumeration` VALUES (null, 'red');
INSERT INTO `enumeration` VALUES (null, 'refusal');
INSERT INTO `enumeration` VALUES (null, 'rejected');
INSERT INTO `enumeration` VALUES (null, 'reran');
INSERT INTO `enumeration` VALUES (null, 'resolved');
INSERT INTO `enumeration` VALUES (null, 'scanner');
INSERT INTO `enumeration` VALUES (null, 'screening');
INSERT INTO `enumeration` VALUES (null, 'sent');
INSERT INTO `enumeration` VALUES (null, 'sessionid');
INSERT INTO `enumeration` VALUES (null, 'splicing');
INSERT INTO `enumeration` VALUES (null, 's_shelf');
INSERT INTO `enumeration` VALUES (null, 's_shore');
INSERT INTO `enumeration` VALUES (null, 'status');
INSERT INTO `enumeration` VALUES (null, 'subject');
INSERT INTO `enumeration` VALUES (null, 'text');
INSERT INTO `enumeration` VALUES (null, 'title');
INSERT INTO `enumeration` VALUES (null, 'uncertain');
INSERT INTO `enumeration` VALUES (null, 'unclassified');
INSERT INTO `enumeration` VALUES (null, 'unknown');
INSERT INTO `enumeration` VALUES (null, 'unresolved');
INSERT INTO `enumeration` VALUES (null, 'urgent');
INSERT INTO `enumeration` VALUES (null, 'utr3');
INSERT INTO `enumeration` VALUES (null, 'utr5');
INSERT INTO `enumeration` VALUES (null, 'valid');
INSERT INTO `enumeration` VALUES (null, 'visit');
INSERT INTO `enumeration` VALUES (null, 'visual');
INSERT INTO `enumeration` VALUES (null, 'volume');
INSERT INTO `enumeration` VALUES (null, 'warning');
INSERT INTO `enumeration` VALUES (null, 'withdrawal');

-- fill en-CA label
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'yes' FROM `enumeration` JOIN `language` WHERE `name` ='yes' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'no' FROM `enumeration` JOIN `language` WHERE `name` ='no' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'true' FROM `enumeration` JOIN `language` WHERE `name` ='true' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'false' FROM `enumeration` JOIN `language` WHERE `name` ='false' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'pass' FROM `enumeration` JOIN `language` WHERE `name` ='pass' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'fail' FROM `enumeration` JOIN `language` WHERE `name` ='fail' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'A' FROM `enumeration` JOIN `language` WHERE `name` ='A' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'C' FROM `enumeration` JOIN `language` WHERE `name` ='C' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'G' FROM `enumeration` JOIN `language` WHERE `name` ='G' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'T' FROM `enumeration` JOIN `language` WHERE `name` ='T' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'female' FROM `enumeration` JOIN `language` WHERE `name` ='female' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'male' FROM `enumeration` JOIN `language` WHERE `name` ='male' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, '1st cousin' FROM `enumeration` JOIN `language` WHERE `name` ='1st_cousin' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'abnormal' FROM `enumeration` JOIN `language` WHERE `name` ='abnormal' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'acknowledged' FROM `enumeration` JOIN `language` WHERE `name` ='acknowledged' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'all' FROM `enumeration` JOIN `language` WHERE `name` ='all' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'answered' FROM `enumeration` JOIN `language` WHERE `name` ='answered' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'approval' FROM `enumeration` JOIN `language` WHERE `name` ='approval' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'assigned' FROM `enumeration` JOIN `language` WHERE `name` ='assigned' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'assignee' FROM `enumeration` JOIN `language` WHERE `name` ='assignee' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'battery' FROM `enumeration` JOIN `language` WHERE `name` ='battery' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'benign' FROM `enumeration` JOIN `language` WHERE `name` ='benign' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'candid' FROM `enumeration` JOIN `language` WHERE `name` ='candid' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'category' FROM `enumeration` JOIN `language` WHERE `name` ='category' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'CDMR' FROM `enumeration` JOIN `language` WHERE `name` ='CDMR' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'center ID' FROM `enumeration` JOIN `language` WHERE `name` ='centerid' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'certified' FROM `enumeration` JOIN `language` WHERE `name` ='certified' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'cleaned' FROM `enumeration` JOIN `language` WHERE `name` ='cleaned' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'closed' FROM `enumeration` JOIN `language` WHERE `name` ='closed' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'comment' FROM `enumeration` JOIN `language` WHERE `name` ='comment' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'complete' FROM `enumeration` JOIN `language` WHERE `name` ='complete' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'created' FROM `enumeration` JOIN `language` WHERE `name` ='created' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'D' FROM `enumeration` JOIN `language` WHERE `name` ='D' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'de novo' FROM `enumeration` JOIN `language` WHERE `name` ='de_novo' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'DMR' FROM `enumeration` JOIN `language` WHERE `name` ='DMR' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'do not know' FROM `enumeration` JOIN `language` WHERE `name` ='do_not_know' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'emailed' FROM `enumeration` JOIN `language` WHERE `name` ='emailed' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'exclude' FROM `enumeration` JOIN `language` WHERE `name` ='exclude' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'excluded' FROM `enumeration` JOIN `language` WHERE `name` ='excluded' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'exonic' FROM `enumeration` JOIN `language` WHERE `name` ='exonic' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'failure' FROM `enumeration` JOIN `language` WHERE `name` ='failure' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'feedback' FROM `enumeration` JOIN `language` WHERE `name` ='feedback' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'full sibling' FROM `enumeration` JOIN `language` WHERE `name` ='full_sibling' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'gain' FROM `enumeration` JOIN `language` WHERE `name` ='gain' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'green' FROM `enumeration` JOIN `language` WHERE `name` ='green' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'half sibling' FROM `enumeration` JOIN `language` WHERE `name` ='half_sibling' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'hardcopy' FROM `enumeration` JOIN `language` WHERE `name` ='hardcopy' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'high' FROM `enumeration` JOIN `language` WHERE `name` ='high' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'human' FROM `enumeration` JOIN `language` WHERE `name` ='human' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'I' FROM `enumeration` JOIN `language` WHERE `name` ='I' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'immediate' FROM `enumeration` JOIN `language` WHERE `name` ='immediate' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'in progress' FROM `enumeration` JOIN `language` WHERE `name` ='in_progress' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'inserted' FROM `enumeration` JOIN `language` WHERE `name` ='inserted' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'inserted flag' FROM `enumeration` JOIN `language` WHERE `name` ='inserted_flag' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'instrument' FROM `enumeration` JOIN `language` WHERE `name` ='instrument' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'in training' FROM `enumeration` JOIN `language` WHERE `name` ='in_training' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'invalid' FROM `enumeration` JOIN `language` WHERE `name` ='invalid' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'island' FROM `enumeration` JOIN `language` WHERE `name` ='island' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'last updated by' FROM `enumeration` JOIN `language` WHERE `name` ='lastupdatedby' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'loss' FROM `enumeration` JOIN `language` WHERE `name` ='loss' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'low' FROM `enumeration` JOIN `language` WHERE `name` ='low' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'maternal' FROM `enumeration` JOIN `language` WHERE `name` ='maternal' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'metavars' FROM `enumeration` JOIN `language` WHERE `name` ='metavars' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'module' FROM `enumeration` JOIN `language` WHERE `name` ='module' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'mri upload' FROM `enumeration` JOIN `language` WHERE `name` ='mri_upload' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'na' FROM `enumeration` JOIN `language` WHERE `name` ='na' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'ncrnaexonic' FROM `enumeration` JOIN `language` WHERE `name` ='ncrnaexonic' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'new' FROM `enumeration` JOIN `language` WHERE `name` ='new' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'none' FROM `enumeration` JOIN `language` WHERE `name` ='none' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non synonymous' FROM `enumeration` JOIN `language` WHERE `name` ='nonsynonymous' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'normal' FROM `enumeration` JOIN `language` WHERE `name` ='normal' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'not answered' FROM `enumeration` JOIN `language` WHERE `name` ='not_answered' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'not applicable' FROM `enumeration` JOIN `language` WHERE `name` ='not_applicable' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'not certified' FROM `enumeration` JOIN `language` WHERE `name` ='not_certified' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'not excluded' FROM `enumeration` JOIN `language` WHERE `name` ='not excluded' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'not started' FROM `enumeration` JOIN `language` WHERE `name` ='not started' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'n shelf' FROM `enumeration` JOIN `language` WHERE `name` ='n_shelf' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'n shore' FROM `enumeration` JOIN `language` WHERE `name` ='n_shore' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'opened' FROM `enumeration` JOIN `language` WHERE `name` ='opened' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'optimal' FROM `enumeration` JOIN `language` WHERE `name` ='optimal' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'other' FROM `enumeration` JOIN `language` WHERE `name` ='other' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'partial' FROM `enumeration` JOIN `language` WHERE `name` ='partial' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'paternal' FROM `enumeration` JOIN `language` WHERE `name` ='paternal' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'pathogenic' FROM `enumeration` JOIN `language` WHERE `name` ='pathogenic' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'PDF' FROM `enumeration` JOIN `language` WHERE `name` ='pdf' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'pending' FROM `enumeration` JOIN `language` WHERE `name` ='pending' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'priority' FROM `enumeration` JOIN `language` WHERE `name` ='priority' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'profile' FROM `enumeration` JOIN `language` WHERE `name` ='profile' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'questionable' FROM `enumeration` JOIN `language` WHERE `name` ='questionable' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'quiz' FROM `enumeration` JOIN `language` WHERE `name` ='quiz' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'raw' FROM `enumeration` JOIN `language` WHERE `name` ='raw' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'RDMR' FROM `enumeration` JOIN `language` WHERE `name` ='RDMR' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'recycling bin' FROM `enumeration` JOIN `language` WHERE `name` ='recycling bin' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'red' FROM `enumeration` JOIN `language` WHERE `name` ='red' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'refusal' FROM `enumeration` JOIN `language` WHERE `name` ='refusal' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'rejected' FROM `enumeration` JOIN `language` WHERE `name` ='rejected' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'reran' FROM `enumeration` JOIN `language` WHERE `name` ='reran' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'resolved' FROM `enumeration` JOIN `language` WHERE `name` ='resolved' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'scanner' FROM `enumeration` JOIN `language` WHERE `name` ='scanner' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'screening' FROM `enumeration` JOIN `language` WHERE `name` ='screening' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'sent' FROM `enumeration` JOIN `language` WHERE `name` ='sent' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'sessionid' FROM `enumeration` JOIN `language` WHERE `name` ='sessionid' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'splicing' FROM `enumeration` JOIN `language` WHERE `name` ='splicing' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 's shelf' FROM `enumeration` JOIN `language` WHERE `name` ='s_shelf' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 's shore' FROM `enumeration` JOIN `language` WHERE `name` ='s_shore' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'status' FROM `enumeration` JOIN `language` WHERE `name` ='status' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'subject' FROM `enumeration` JOIN `language` WHERE `name` ='subject' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'text' FROM `enumeration` JOIN `language` WHERE `name` ='text' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'title' FROM `enumeration` JOIN `language` WHERE `name` ='title' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'uncertain' FROM `enumeration` JOIN `language` WHERE `name` ='uncertain' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'unclassified' FROM `enumeration` JOIN `language` WHERE `name` ='unclassified' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'unknown' FROM `enumeration` JOIN `language` WHERE `name` ='unknown' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'unresolved' FROM `enumeration` JOIN `language` WHERE `name` ='unresolved' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'urgent' FROM `enumeration` JOIN `language` WHERE `name` ='urgent' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'utr3' FROM `enumeration` JOIN `language` WHERE `name` ='utr3' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'utr5' FROM `enumeration` JOIN `language` WHERE `name` ='utr5' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'valid' FROM `enumeration` JOIN `language` WHERE `name` ='valid' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'visit' FROM `enumeration` JOIN `language` WHERE `name` ='visit' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'visual' FROM `enumeration` JOIN `language` WHERE `name` ='visual' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'volume' FROM `enumeration` JOIN `language` WHERE `name` ='volume' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'warning' FROM `enumeration` JOIN `language` WHERE `name` ='warning' AND `language_code` = 'en-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'withdrawal' FROM `enumeration` JOIN `language` WHERE `name` ='withdrawal' AND `language_code` = 'en-CA');


-- fill fr-CA label
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'oui' FROM `enumeration` JOIN `language` WHERE `name` ='yes' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non' FROM `enumeration` JOIN `language` WHERE `name` ='no' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'vrai' FROM `enumeration` JOIN `language` WHERE `name` ='true' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'faux' FROM `enumeration` JOIN `language` WHERE `name` ='false' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'succès' FROM `enumeration` JOIN `language` WHERE `name` ='pass' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'échec' FROM `enumeration` JOIN `language` WHERE `name` ='fail' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'femelle' FROM `enumeration` JOIN `language` WHERE `name` ='female' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'mâle' FROM `enumeration` JOIN `language` WHERE `name` ='male' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'cousin' FROM `enumeration` JOIN `language` WHERE `name` ='1st_cousin' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'anormal' FROM `enumeration` JOIN `language` WHERE `name` ='abnormal' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'tout' FROM `enumeration` JOIN `language` WHERE `name` ='all' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'répondu' FROM `enumeration` JOIN `language` WHERE `name` ='answered' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'approbation' FROM `enumeration` JOIN `language` WHERE `name` ='approval' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'assigné' FROM `enumeration` JOIN `language` WHERE `name` ='assigned' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'assigné' FROM `enumeration` JOIN `language` WHERE `name` ='assignee' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'batterie' FROM `enumeration` JOIN `language` WHERE `name` ='battery' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'bénin' FROM `enumeration` JOIN `language` WHERE `name` ='benign' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'catégorie' FROM `enumeration` JOIN `language` WHERE `name` ='category' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'CDMR' FROM `enumeration` JOIN `language` WHERE `name` ='CDMR' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'ID du centre' FROM `enumeration` JOIN `language` WHERE `name` ='centerid' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'certifié' FROM `enumeration` JOIN `language` WHERE `name` ='certified' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'nettoyé' FROM `enumeration` JOIN `language` WHERE `name` ='cleaned' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'fermé' FROM `enumeration` JOIN `language` WHERE `name` ='closed' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'commentaire' FROM `enumeration` JOIN `language` WHERE `name` ='comment' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'complet' FROM `enumeration` JOIN `language` WHERE `name` ='complete' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'créé' FROM `enumeration` JOIN `language` WHERE `name` ='created' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'ne sais pas' FROM `enumeration` JOIN `language` WHERE `name` ='do_not_know' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'envoyé' FROM `enumeration` JOIN `language` WHERE `name` ='emailed' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'exclus' FROM `enumeration` JOIN `language` WHERE `name` ='exclude' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'exclus' FROM `enumeration` JOIN `language` WHERE `name` ='excluded' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'échec' FROM `enumeration` JOIN `language` WHERE `name` ='failure' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'frère/soeur' FROM `enumeration` JOIN `language` WHERE `name` ='full_sibling' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'vert' FROM `enumeration` JOIN `language` WHERE `name` ='green' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'demi frère/soeur' FROM `enumeration` JOIN `language` WHERE `name` ='half_sibling' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'élevé' FROM `enumeration` JOIN `language` WHERE `name` ='high' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'humain' FROM `enumeration` JOIN `language` WHERE `name` ='human' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'immédiat' FROM `enumeration` JOIN `language` WHERE `name` ='immediate' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'en cours' FROM `enumeration` JOIN `language` WHERE `name` ='in_progress' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'inséré' FROM `enumeration` JOIN `language` WHERE `name` ='inserted' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'en formation' FROM `enumeration` JOIN `language` WHERE `name` ='in_training' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'invalide' FROM `enumeration` JOIN `language` WHERE `name` ='invalid' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'ile' FROM `enumeration` JOIN `language` WHERE `name` ='island' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'perte' FROM `enumeration` JOIN `language` WHERE `name` ='loss' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'faible' FROM `enumeration` JOIN `language` WHERE `name` ='low' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'maternel' FROM `enumeration` JOIN `language` WHERE `name` ='maternal' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'nouveau' FROM `enumeration` JOIN `language` WHERE `name` ='new' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'aucun' FROM `enumeration` JOIN `language` WHERE `name` ='none' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'différent' FROM `enumeration` JOIN `language` WHERE `name` ='nonsynonymous' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'normal' FROM `enumeration` JOIN `language` WHERE `name` ='normal' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non répondu' FROM `enumeration` JOIN `language` WHERE `name` ='not_answered' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non applicable' FROM `enumeration` JOIN `language` WHERE `name` ='not_applicable' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non certifié' FROM `enumeration` JOIN `language` WHERE `name` ='not_certified' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'inclus' FROM `enumeration` JOIN `language` WHERE `name` ='not excluded' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non démarré' FROM `enumeration` JOIN `language` WHERE `name` ='not started' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'ouvert' FROM `enumeration` JOIN `language` WHERE `name` ='opened' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'autre' FROM `enumeration` JOIN `language` WHERE `name` ='other' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'partiel' FROM `enumeration` JOIN `language` WHERE `name` ='partial' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'paternel' FROM `enumeration` JOIN `language` WHERE `name` ='paternal' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'pathogène' FROM `enumeration` JOIN `language` WHERE `name` ='pathogenic' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'en attente' FROM `enumeration` JOIN `language` WHERE `name` ='pending' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'priorité' FROM `enumeration` JOIN `language` WHERE `name` ='priority' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'profil' FROM `enumeration` JOIN `language` WHERE `name` ='profile' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'questionnable' FROM `enumeration` JOIN `language` WHERE `name` ='questionable' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'brut' FROM `enumeration` JOIN `language` WHERE `name` ='raw' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'rouge' FROM `enumeration` JOIN `language` WHERE `name` ='red' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'refus' FROM `enumeration` JOIN `language` WHERE `name` ='refusal' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'rejet' FROM `enumeration` JOIN `language` WHERE `name` ='rejected' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'résolut' FROM `enumeration` JOIN `language` WHERE `name` ='resolved' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'envoyé' FROM `enumeration` JOIN `language` WHERE `name` ='sent' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'ID de session' FROM `enumeration` JOIN `language` WHERE `name` ='sessionid' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'statut' FROM `enumeration` JOIN `language` WHERE `name` ='status' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'sujet' FROM `enumeration` JOIN `language` WHERE `name` ='subject' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'texte' FROM `enumeration` JOIN `language` WHERE `name` ='text' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'titre' FROM `enumeration` JOIN `language` WHERE `name` ='title' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'incertain' FROM `enumeration` JOIN `language` WHERE `name` ='uncertain' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non classifié' FROM `enumeration` JOIN `language` WHERE `name` ='unclassified' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'inconnu' FROM `enumeration` JOIN `language` WHERE `name` ='unknown' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'non résolut' FROM `enumeration` JOIN `language` WHERE `name` ='unresolved' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'valide' FROM `enumeration` JOIN `language` WHERE `name` ='valid' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'visite' FROM `enumeration` JOIN `language` WHERE `name` ='visit' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'visuel' FROM `enumeration` JOIN `language` WHERE `name` ='visual' AND `language_code` = 'fr-CA');
INSERT INTO enumeration_label (SELECT `EnumerationID`, `language_id`, 'retrait' FROM `enumeration` JOIN `language` WHERE `name` ='withdrawal' AND `language_code` = 'fr-CA');

