SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE bids_scan_type;
LOCK TABLE bids_scan_type WRITE;
LOAD DATA LOCAL INFILE 'bids_scan_type.tsv' INTO TABLE bids_scan_type
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
