SET FOREIGN_KEY_CHECKS=0;
LOCK TABLE caveat_options WRITE;
TRUNCATE TABLE caveat_options;
LOAD DATA LOCAL INFILE 'caveat_options.tsv' INTO TABLE caveat_options
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
