SET FOREIGN_KEY_CHECKS=0;
LOCK TABLE ConfigSettings WRITE;
TRUNCATE TABLE ConfigSettings;
LOAD DATA LOCAL INFILE 'ConfigSettings.tsv' INTO TABLE ConfigSettings
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
