SET FOREIGN_KEY_CHECKS=0;
LOCK TABLE ExternalLinkTypes WRITE;
TRUNCATE TABLE ExternalLinkTypes;
LOAD DATA LOCAL INFILE 'ExternalLinkTypes.tsv' INTO TABLE ExternalLinkTypes
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
