SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE ImagingFileTypes;
LOCK TABLE ImagingFileTypes WRITE;
LOAD DATA LOCAL INFILE 'ImagingFileTypes.tsv' INTO TABLE ImagingFileTypes
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
