SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE menu_categories;
LOCK TABLE menu_categories WRITE;
LOAD DATA LOCAL INFILE 'menu_categories.tsv' INTO TABLE menu_categories
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
