SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE parameter_type;
LOCK TABLE parameter_type WRITE;
LOAD DATA LOCAL INFILE 'parameter_type.tsv' INTO TABLE parameter_type
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
