/*M!999999\- enable the sandbox mode */ 
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `ConfigI18n`;
LOCK TABLES `ConfigI18n` WRITE;
INSERT INTO `ConfigI18n` (`Value`, `ConfigID`, `LanguageID`) VALUES ('Base de données de démonstration LORIS',3,2);
INSERT INTO `ConfigI18n` (`Value`, `ConfigID`, `LanguageID`) VALUES ('<h3>Exemple de description de l\'étude</h3>\n <p>Il s\'agit d\'un exemple de description pour cette étude, car il s\'agit d\'une nouvelle installation LORIS qui n\'a pas encore personnalisé ce texte.</p>\n <p>Un administrateur LORIS peut personnaliser ce texte dans le module de configuration, sous l\'option de configuration intitulée « Description de l\'étude ».</p>\n <h3>Liens utiles</h3>\n <ul>\n <li><a href=\"https://github.com/aces/Loris\" >Répertoire GitHub LORIS</a></li>\n <li><a href=\"https://github.com/aces/Loris/wiki/Setup\" >Guide d\'installation LORIS</a></li>\n <li><a href=\"https://www.youtube.com/watch?v=2Syd_BUbl5A\" >Vidéo d\'un loris sur YouTube</a></li>',42,2);
INSERT INTO `ConfigI18n` (`Value`, `ConfigID`, `LanguageID`) VALUES ('Cette base de données fournit un mécanisme en ligne permettant de stocker à la fois les données d\'imagerie et les données comportementales recueillies à divers endroits. Dans ce cadre, plusieurs outils sont disponibles pour rendre ce processus aussi efficace et simple que possible. Pour obtenir des informations plus détaillées sur tout aspect de la base de données, veuillez cliquer sur l\'icône Aide en haut à droite. Sinon, n\'hésitez pas à nous contacter au DCC. Nous nous efforçons de rendre la collecte de données presque amusante.',48,2);
INSERT INTO `ConfigI18n` (`Value`, `ConfigID`, `LanguageID`) VALUES ('ロリスデモンストレーションデータベース',3,3);
INSERT INTO `ConfigI18n` (`Value`, `ConfigID`, `LanguageID`) VALUES ('<h3>研究の説明例</h3>\n<p>これは、この研究の説明例です。LORIS は新規にインストールされたため、まだカスタマイズされていません。</p>\n<p>LORIS 管理者は、設定モジュールの「研究の説明」という設定オプションでこのテキストをカスタマイズできます。</p>\n<h3>役立つリンク</h3>\n<ul>\n<li><a href=\"https://github.com/aces/Loris\" >LORIS GitHub リポジトリ</a></li>\n<li><a href=\"https://github.com/aces/Loris/wiki/Setup\" >LORIS セットアップガイド</a></li>\n<li><a href=\"https://www.youtube.com/watch?v=2Syd_BUbl5A\" >YouTube のロリスの動画</a></li>\n</ul>',42,3);
INSERT INTO `ConfigI18n` (`Value`, `ConfigID`, `LanguageID`) VALUES ('このデータベースは、様々な場所で収集された画像データと行動データの両方をオンラインで保存するための仕組みを提供します。このフレームワークには、このプロセスを可能な限り効率的かつシンプルにするためのツールがいくつか用意されています。データベースに関する詳細な情報については、右上のヘルプアイコンをクリックしてください。それ以外の場合\nは、DCCまでお気軽にお問い合わせください。私たちは、データ収集を楽しいものにすることを目指しています。',48,3);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
