SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `certification`;
LOCK TABLES `certification` WRITE;
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (8,1,'2016-06-14',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (9,3,'2016-06-29',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (11,4,'2016-12-31',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (12,2,'2008-01-04',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (13,18,'2003-03-03',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (14,18,'2003-04-05',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (15,25,'2004-05-06',NULL,2,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (16,21,'2016-05-05',NULL,2,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (17,21,'2016-05-05',NULL,1,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (18,16,'2008-09-08',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (19,16,'2009-09-08',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (20,14,'2011-09-01',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (21,22,'2005-09-07',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (22,22,'2016-05-05',NULL,1,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (23,10,'2014-04-04',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (24,10,'2016-05-01',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (25,24,'2016-05-06',NULL,2,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (26,24,'2016-05-09',NULL,1,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (27,17,'2006-09-01',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (28,17,'2011-11-11',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (29,26,'2016-05-04',NULL,2,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (30,26,'2016-04-03',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (31,23,'2009-08-05',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (32,23,'2000-02-01',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (33,27,'2016-05-09',NULL,2,'in_training','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (34,27,'2005-09-04',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (35,11,'2009-09-08',NULL,1,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (36,8,'2000-01-01',NULL,2,'certified','');
INSERT INTO `certification` (`certID`, `examinerID`, `date_cert`, `visit_label`, `testID`, `pass`, `comment`) VALUES (37,8,'2000-01-01',NULL,1,'certified','');
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
