SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `examiners`;
LOCK TABLES `examiners` WRITE;
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (1,'Katrina Cane',1,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (2,'Marcel Getter',1,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (4,'Brad Bitt',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (5,'Rosie Oh',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (6,'Kimmy Ellis',1,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (7,'Angelina Joe',1,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (8,'DCC Examiner',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (9,'Christina Smith',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (10,'Dave MacDonald',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (16,'John Smith',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (17,'Jane Doe',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (18,'Alex Li',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (19,'Leigh Mac',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (20,'Rid Ah',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (21,'Hazel Hurr',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (22,'Sarah Lo',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (23,'Ray Sin',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (24,'Harvey Cohen',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (25,'Ellie Richman',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (26,'Christine Brose',0,NULL);
INSERT INTO `examiners` (`examinerID`, `full_name`, `radiologist`, `userID`) VALUES (27,'Rosie Lee',0,NULL);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
