SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `feedback_mri_comment_types`;
LOCK TABLES `feedback_mri_comment_types` WRITE;
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (1,'Geometric distortion','volume','a:2:{s:5:\"field\";s:20:\"Geometric_distortion\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:4:\"Good\";i:2;s:4:\"Fair\";i:3;s:4:\"Poor\";i:4;s:12:\"Unacceptable\";}}');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (2,'Intensity artifact','volume','a:2:{s:5:\"field\";s:18:\"Intensity_artifact\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:4:\"Good\";i:2;s:4:\"Fair\";i:3;s:4:\"Poor\";i:4;s:12:\"Unacceptable\";}}');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (3,'Movement artifact','volume','a:2:{s:5:\"field\";s:30:\"Movement_artifacts_within_scan\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:4:\"None\";i:2;s:15:\"Slight Movement\";i:3;s:12:\"Poor Quality\";i:4;s:12:\"Unacceptable\";}}');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (4,'Packet movement artifact','volume','a:2:{s:5:\"field\";s:31:\"Movement_artifacts_between_packets\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:4:\"None\";i:2;s:15:\"Slight Movement\";i:3;s:12:\"Poor Quality\";i:4;s:12:\"Unacceptable\";}}');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (5,'Coverage','volume','a:2:{s:5:\"field\";s:8:\"Coverage\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:4:\"Good\";i:2;s:4:\"Fair\";i:3;s:5:\"Limit\";i:4;s:12:\"Unacceptable\";}}');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (6,'Overall','volume','');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (7,'Subject','visit','');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (8,'Dominant Direction Artifact (DWI ONLY)','volume','a:2:{s:5:\"field\";s:14:\"Color_Artifact\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:4:\"Good\";i:2;s:4:\"Fair\";i:3;s:4:\"Poor\";i:4;s:12:\"Unacceptable\";}}');
INSERT INTO `feedback_mri_comment_types` (`CommentTypeID`, `CommentName`, `CommentType`, `CommentStatusField`) VALUES (9,'Entropy Rating (DWI ONLY)','volume','a:2:{s:5:\"field\";s:7:\"Entropy\";s:6:\"values\";a:5:{i:0;s:0:\"\";i:1;s:10:\"Acceptable\";i:2;s:10:\"Suspicious\";i:3;s:12:\"Unacceptable\";i:4;s:13:\"Not Available\";}}');
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
