SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `genomic_cpg_annotation`;
LOCK TABLES `genomic_cpg_annotation` WRITE;
INSERT INTO `genomic_cpg_annotation` (`cpg_name`, `address_id_a`, `probe_seq_a`, `address_id_b`, `probe_seq_b`, `design_type`, `color_channel`, `genome_build`, `probe_snp_10`, `gene_name`, `gene_acc_num`, `gene_group`, `island_loc`, `island_relation`, `fantom_promoter_loc`, `dmr`, `enhancer`, `hmm_island_loc`, `reg_feature_loc`, `reg_feature_group`, `dhs`, `platform_id`, `Chromosome`, `Strand`, `EndLoc`, `StartLoc`) VALUES ('CPG_573847',NULL,NULL,NULL,NULL,NULL,'Red',NULL,NULL,NULL,NULL,NULL,NULL,'island',NULL,'DMR',NULL,NULL,NULL,NULL,NULL,1,'chr1','+',11007,11008);
INSERT INTO `genomic_cpg_annotation` (`cpg_name`, `address_id_a`, `probe_seq_a`, `address_id_b`, `probe_seq_b`, `design_type`, `color_channel`, `genome_build`, `probe_snp_10`, `gene_name`, `gene_acc_num`, `gene_group`, `island_loc`, `island_relation`, `fantom_promoter_loc`, `dmr`, `enhancer`, `hmm_island_loc`, `reg_feature_loc`, `reg_feature_group`, `dhs`, `platform_id`, `Chromosome`, `Strand`, `EndLoc`, `StartLoc`) VALUES ('CPG_573848',NULL,NULL,NULL,NULL,NULL,'Red',NULL,NULL,NULL,NULL,NULL,NULL,'island',NULL,'DMR',NULL,NULL,NULL,NULL,NULL,1,'chr1','+',11007,11008);
INSERT INTO `genomic_cpg_annotation` (`cpg_name`, `address_id_a`, `probe_seq_a`, `address_id_b`, `probe_seq_b`, `design_type`, `color_channel`, `genome_build`, `probe_snp_10`, `gene_name`, `gene_acc_num`, `gene_group`, `island_loc`, `island_relation`, `fantom_promoter_loc`, `dmr`, `enhancer`, `hmm_island_loc`, `reg_feature_loc`, `reg_feature_group`, `dhs`, `platform_id`, `Chromosome`, `Strand`, `EndLoc`, `StartLoc`) VALUES ('CPG_573851',NULL,NULL,NULL,NULL,NULL,'Red',NULL,NULL,NULL,NULL,NULL,NULL,'island',NULL,'DMR',NULL,NULL,NULL,NULL,NULL,1,'chr1','+',11007,11008);
INSERT INTO `genomic_cpg_annotation` (`cpg_name`, `address_id_a`, `probe_seq_a`, `address_id_b`, `probe_seq_b`, `design_type`, `color_channel`, `genome_build`, `probe_snp_10`, `gene_name`, `gene_acc_num`, `gene_group`, `island_loc`, `island_relation`, `fantom_promoter_loc`, `dmr`, `enhancer`, `hmm_island_loc`, `reg_feature_loc`, `reg_feature_group`, `dhs`, `platform_id`, `Chromosome`, `Strand`, `EndLoc`, `StartLoc`) VALUES ('CPG_573852',NULL,NULL,NULL,NULL,NULL,'Red',NULL,NULL,NULL,NULL,NULL,NULL,'island',NULL,'DMR',NULL,NULL,NULL,NULL,NULL,1,'chr1','+',11007,11008);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
