SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `issues_comments`;
LOCK TABLES `issues_comments` WRITE;
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (1,14,'2016-09-01 18:49:36','admin','Feedback');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (2,15,'2016-09-01 18:52:32','admin','Description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (3,15,'2016-09-02 20:24:09','tester','comment for stella. ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (4,15,'2016-09-02 20:27:13','admin','update');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (5,15,'2016-09-02 20:28:38','tester','another comment for stella. ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (6,16,'2016-09-02 20:30:39','tester','blah blah blah');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (7,17,'2016-09-02 20:32:21','tester','adding a new comment, i only have reporter permissions. ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (8,18,'2016-09-02 20:33:48','tester','assigned to: admin\r\nwatching; no\r\nothers watching: admin');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (9,18,'2016-09-02 20:34:17','tester','adding comment.  ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (10,19,'2016-09-02 21:59:56','tester','hey stella do you see this?  did Admin get an Assignee notification?  Did Test User also get a watching notification? ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (11,20,'2016-09-02 22:02:30','tester','no one should get a notification for this new ticket. ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (12,20,'2016-09-02 22:04:38','tester','with this update, Admin should get an email notification saying that they\'ve been assigned to this [PRE-EXISTING] ticket');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (13,20,'2016-09-02 22:11:17','tester','user can add comment if they reported it. ');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (14,15,'2016-09-02 22:12:32','tester','reporter-level user can add comment if they are neither assignee nor reporter');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (15,17,'2016-09-02 22:18:44','tester','verifying that a second comment doesn\'t get stored in the description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (16,21,'2016-09-02 23:45:40','tester','i can\'t write another description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (17,22,'2016-09-02 23:46:33','tester','i can\'t write another description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (18,23,'2016-09-02 23:46:49','tester','i can\'t write another description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (19,24,'2016-09-02 23:46:57','tester','i can\'t write another description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (20,25,'2016-09-02 23:47:01','tester','i can\'t write another description');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (21,26,'2016-09-07 01:19:22','admin','aaaaaa');
INSERT INTO `issues_comments` (`issueCommentID`, `issueID`, `dateAdded`, `addedBy`, `issueComment`) VALUES (22,27,'2016-09-07 01:38:07','admin','aaaaa');
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
