SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `LorisMenuPermissions`;
LOCK TABLES `LorisMenuPermissions` WRITE;
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (32,1);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (9,2);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (29,2);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (30,2);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (31,4);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (7,10);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (8,10);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (9,10);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (7,11);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (8,11);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (18,11);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (11,12);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (11,13);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (12,14);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (10,17);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (19,18);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (20,18);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (16,19);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (22,21);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (33,22);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (15,23);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (15,24);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (14,25);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (9,26);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (24,28);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (20,29);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (23,30);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (25,33);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (25,34);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (21,35);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (34,37);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (17,38);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (27,39);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (27,40);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (19,41);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (13,43);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (13,44);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (28,45);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (15,47);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (15,48);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (32,49);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (32,50);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (36,53);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (36,54);
INSERT INTO `LorisMenuPermissions` (`MenuID`, `PermID`) VALUES (36,55);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
