SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `Login_Summary_Statistics`;
LOCK TABLES `Login_Summary_Statistics` WRITE;
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('EEG Recording','All Projects',10,7);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('EEG Recording','Pumpernickel',10,7);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Female Participant','All Projects',334,1);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Female Participant','Challah',47,1);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Female Participant','Pumpernickel',225,1);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Female Participant','Rye',62,1);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Instrument','All Projects',5,5);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Instrument','Challah',5,5);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Instrument','Pumpernickel',5,5);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Instrument','Rye',2,5);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Male Participant','All Projects',328,2);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Male Participant','Challah',60,2);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Male Participant','Pumpernickel',210,2);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Male Participant','Rye',58,2);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Scan','All Projects',311,6);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Scan','Challah',23,6);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Scan','Pumpernickel',247,6);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Scan','Rye',41,6);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Site','All Projects',4,3);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Site','Challah',1,3);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Site','Pumpernickel',4,3);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Site','Rye',1,3);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Visit','All Projects',1133,4);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Visit','Challah',147,4);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Visit','Pumpernickel',855,4);
INSERT INTO `Login_Summary_Statistics` (`Title`, `Project`, `Value`, `QueryOrder`) VALUES ('Visit','Rye',131,4);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
