SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `mri_scan_type`;
LOCK TABLES `mri_scan_type` WRITE;
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (40,'fMRI');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (41,'flair');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (44,'t1');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (45,'t2');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (46,'pd');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (47,'mrs');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (48,'dti');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (49,'t1relx');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (50,'dct2e1');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (51,'dct2e2');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (52,'scout');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (53,'tal_msk');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (54,'cocosco_cls');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (55,'clean_cls');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (56,'em_cls');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (57,'seg');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (58,'white_matter');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (59,'gray_matter');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (60,'csf_matter');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (61,'nlr_masked');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (62,'pve');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (63,'fieldmapBOLD');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (64,'fieldmapDWI');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (65,'dwi65');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (66,'dwi25');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (999,'unknown');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1000,'NA');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1001,'DTIPrepReg');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1002,'DTIPrepNoReg');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1003,'DTIPrepDTIColorFA');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1004,'DTIPrepDTIFA');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1005,'DTIPrepDTIMD');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1006,'DTIPrepBaseline');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1007,'DTPrepIDWI');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1008,'DTIPrepDTI');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1009,'DTIPrepBetMask');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1010,'DTIPrepQCReport');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1011,'DTIPrepXMLQCReport');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1012,'DTIPrepXMLProtocol');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1013,'-defaced');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1014,'t2-defaced');
INSERT INTO `mri_scan_type` (`ID`, `Name`) VALUES (1015,'t1-defaced');
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
