SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `notification_modules_services_rel`;
LOCK TABLES `notification_modules_services_rel` WRITE;
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (9,2);
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (10,2);
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (11,2);
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (12,2);
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (13,2);
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (14,2);
INSERT INTO `notification_modules_services_rel` (`module_id`, `service_id`) VALUES (15,2);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
