SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `physiological_task_event_hed_rel`;
LOCK TABLES `physiological_task_event_hed_rel` WRITE;
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (1,1,1165,NULL,0,NULL,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (2,1,542,NULL,1,1,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (3,2,1164,NULL,0,NULL,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (4,3,1165,NULL,0,NULL,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (5,4,1166,NULL,0,NULL,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (6,5,1167,NULL,0,NULL,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (7,6,1168,NULL,0,NULL,0,NULL);
INSERT INTO `physiological_task_event_hed_rel` (`ID`, `PhysiologicalTaskEventID`, `HEDTagID`, `TagValue`, `HasPairing`, `PairRelID`, `AdditionalMembers`, `TaggedBy`) VALUES (8,7,1169,NULL,0,NULL,0,NULL);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
