SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `physiological_coord_system_name`;
LOCK TABLES `physiological_coord_system_name` WRITE;
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (1,'Not registered',NULL,NULL);
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (2,'ACPC','RAS','anterior commissure');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (3,'Allen Institute','RAS','Bregma point');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (4,'Analyze','LAS','');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (5,'BTi/4D','ALS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (6,'CTF','ALS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (7,'CTF MRI','ALS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (8,'CTF gradiometer','ALS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (9,'CapTrak','RAS','approximately between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (10,'Chieti ITAB','RAS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (11,'DICOM','LPS','centre of MRI gradient coil');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (12,'EEGLAB','ALS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (13,'FreeSurfer','RAS','center of isotropic 1mm 256x256x256 volume');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (14,'MNI','RAS','anterior commissure');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (15,'NIfTI','RAS','');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (16,'Neuromag/Elekta/Megin','RAS','between the ears');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (17,'Paxinos-Franklin','RSP','Bregma point');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (18,'Scanner RAS (scanras)','RAS','scanner origin');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (19,'Talairach-Tournoux','RAS','anterior commissure');
INSERT INTO `physiological_coord_system_name` (`PhysiologicalCoordSystemNameID`, `Name`, `Orientation`, `Origin`) VALUES (20,'Yokogawa','ALS','center of device');
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
