SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `scan_type_parameter`;
LOCK TABLES `scan_type_parameter` WRITE;
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1000,1,63,'repetition_time',347.0000,667.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1001,1,63,'echo_time',5.1900,7.6500,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1002,1,44,'repetition_time',2400.0000,2400.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1003,1,44,'echo_time',2.0000,4.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1004,1,44,'inversion_time',1200.0000,1200.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1005,1,45,'repetition_time',3200.0000,3200.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1006,1,45,'echo_time',384.0000,528.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1007,1,40,'repetition_time',2500.0000,2500.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1008,1,40,'echo_time',27.0000,27.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1009,1,40,'time',130.0000,130.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1010,1,66,'repetition_time',10404.0000,14600.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1011,1,66,'echo_time',88.0000,102.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1012,1,66,'time',25.0000,27.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1013,1,65,'repetition_time',10200.0000,13000.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1014,1,65,'echo_time',88.0000,105.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1015,1,65,'time',65.0000,66.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1016,1,64,'repetition_time',489.0000,489.0000,NULL);
INSERT INTO `scan_type_parameter` (`ScanTypeParameterID`, `ScanTypeParameterGroupID`, `ScanType`, `HeaderName`, `ValidMin`, `ValidMax`, `ValidRegex`) VALUES (1017,1,64,'echo_time',3.1900,5.6500,NULL);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
