SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `visit_subproject_rel`;
LOCK TABLES `visit_subproject_rel` WRITE;
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (1,1);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (1,2);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (2,1);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (2,2);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (3,1);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (3,2);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (3,3);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (3,4);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (4,3);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (4,4);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (5,3);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (5,4);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (6,3);
INSERT INTO `visit_subproject_rel` (`VisitID`, `SubprojectID`) VALUES (6,4);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
