SET FOREIGN_KEY_CHECKS=0;
LOCK TABLE shipment_status WRITE;
TRUNCATE TABLE shipment_status;
LOAD DATA LOCAL INFILE 'shipment_status.tsv' INTO TABLE shipment_status
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
