SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE StatisticsTabs;
LOCK TABLE StatisticsTabs WRITE;
LOAD DATA LOCAL INFILE 'StatisticsTabs.tsv' INTO TABLE StatisticsTabs
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
