SET FOREIGN_KEY_CHECKS=0;
LOCK TABLE test_subgroups WRITE;
TRUNCATE TABLE test_subgroups;
LOAD DATA LOCAL INFILE 'test_subgroups.tsv' INTO TABLE test_subgroups
 IGNORE 1 LINES;
SET FOREIGN_KEY_CHECKS=1;
