name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Install dependencies
      run: sudo apt-get 
    - name: Install dependencies
      run: sudo apt-get install -y libapparmor1
    - name: Install dependencies
      run: pecl install -f ast-1.0.3
    - name: Install dependencies
      run: sudo apt-get install nodejs-dev node-gyp libssl1.0-dev npm     
    - name: Install dependencies
      run: make dev
    - name: Run test suite
      run: npm run tests:integration

      
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
